'use client';
import { useEffect,useState } from 'react';
import { createClient } from '../../../utils/supabase/client';

async function tok(){const s=createClient();const {data:{session}}=await s.auth.getSession();return session?.access_token||''}
export default function Seguimiento(){
 const now=new Date();const[anio,setAnio]=useState(now.getFullYear()),[semana,setSemana]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function call(url,options={}){const t=await tok();const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error);return d}
 async function load(){setLoading(true);setError('');try{const d=await call(`/api/vigilancia/seguimiento?anio=${anio}&semana=${semana||''}`);setAnio(d.anio);setSemana(d.semana);setRows(d.rows||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function status(tipo,id,estado){const obs=estado==='REQUIERE_CORRECCION'?prompt('Indique la corrección requerida:')||'': '';try{await call('/api/vigilancia/seguimiento',{method:'PATCH',body:JSON.stringify({tipo,id,estado,observacion:obs})});await load()}catch(e){setError(e.message)}}
 const sent=rows.filter(x=>x.boletin?.estado==='ENVIADO'||x.boletin?.estado==='CERRADO').length,pending=rows.length-sent;
 return <main className="vig-shell"><div className="vig-wrap"><div className="vig-header"><div><span className="vig-badge">VIGILANCIA EPIDEMIOLÓGICA</span><h1>Seguimiento semanal</h1></div><a className="vig-button light" href="/vigilancia/panel">Volver</a></div>
 <section className="vig-card"><div className="vig-actions"><label className="vig-field">Año<input type="number" value={anio} onChange={e=>setAnio(Number(e.target.value))}/></label><label className="vig-field">Semana epidemiológica<input type="number" min="1" max="53" value={semana} onChange={e=>setSemana(Number(e.target.value))}/></label><button className="vig-button" onClick={load}>CONSULTAR</button></div></section>
 <section className="vig-grid"><div className="vig-stat">Establecimientos<strong>{rows.length}</strong></div><div className="vig-stat">Notificaron<strong>{sent}</strong></div><div className="vig-stat">Pendientes<strong>{pending}</strong></div><div className="vig-stat">Cumplimiento<strong>{rows.length?Math.round(sent*100/rows.length):0}%</strong></div></section>
 {error&&<p className="vig-error">{error}</p>}{loading?<section className="vig-card">Cargando…</section>:<section className="vig-card"><div className="vig-table-wrap"><table className="vig-table"><thead><tr><th>Municipio / clínica</th><th>Boletín</th><th>Casos</th><th>Lista nominal</th><th>Fichas</th></tr></thead><tbody>{rows.map(r=><tr key={r.clinica.id}><td><strong>{r.clinica.nombre}</strong><br/>{r.clinica.municipio} · {r.clinica.codigo}</td><td><span className={`vig-status ${r.boletin?'ok':'pending'}`}>{r.boletin?.estado||'NO NOTIFICÓ'}</span><br/>{r.boletin?.enviado_at?new Date(r.boletin.enviado_at).toLocaleString('es-HN'):'—'}</td><td>{r.total}</td><td>{r.lista?<><strong>{r.lista.estado}</strong><div className="vig-actions"><button onClick={()=>status('LISTA',r.lista.id,'RECIBIDA')}>Recibida</button><button onClick={()=>status('LISTA',r.lista.id,'REQUIERE_CORRECCION')}>Corregir</button><button onClick={()=>status('LISTA',r.lista.id,'VALIDADA')}>Validar</button></div></>:'—'}</td><td>{r.fichas.length?r.fichas.map(f=><div key={f.id} className="vig-mini"><strong>{f.vigilancia_enfermedades?.nombre}</strong> · {f.paciente_id}<br/>{f.estado}<div className="vig-actions"><button onClick={()=>status('FICHA',f.id,'RECIBIDA')}>Recibida</button><button onClick={()=>status('FICHA',f.id,'REQUIERE_CORRECCION')}>Corregir</button><button onClick={()=>status('FICHA',f.id,'VALIDADA')}>Validar</button></div></div>):'—'}</td></tr>)}</tbody></table></div></section>}
 </div></main>
}
