'use client';
import {useEffect,useMemo,useState} from 'react';import {useParams,useRouter,useSearchParams} from 'next/navigation';import {createClient} from '../../../utils/supabase/client';
const CURSO_KEY='encuestas_olancho_sesion_en_curso';
export default function InstrumentoPage(){const params=useParams(),router=useRouter(),sp=useSearchParams(),codigo=params?.codigo,sesion=sp.get('sesion'),folio=sp.get('folio'),modo=sp.get('modo');const[preguntas,setPreguntas]=useState([]),[indice,setIndice]=useState(0),[respuestas,setRespuestas]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[guardando,setGuardando]=useState(false),[enviado,setEnviado]=useState(false),[operado,setOperado]=useState(null);const aplicacion=modo==='aplicacion'&&!!sesion;const avanceKey=sesion?`encuestas_olancho_avance_${sesion}`:null;
useEffect(()=>{if(!aplicacion)return;try{const raw=localStorage.getItem(avanceKey);if(raw){const a=JSON.parse(raw);if(a.respuestas&&typeof a.respuestas==='object')setRespuestas(a.respuestas);if(Number.isInteger(a.indice))setIndice(Math.max(0,a.indice));if(typeof a.operado==='boolean')setOperado(a.operado);}const url=`/encuestas/${codigo}?sesion=${sesion}&folio=${encodeURIComponent(folio||'')}&modo=aplicacion`;localStorage.setItem(CURSO_KEY,JSON.stringify({url,sesion_id:sesion,folio,codigo}));}catch{}},[aplicacion,avanceKey,codigo,sesion,folio]);
useEffect(()=>{let a=true;(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data,error:e}=await s.rpc('obtener_preguntas_encuesta',{p_codigo:codigo});if(!a)return;if(e)setError('No fue posible cargar las preguntas.');else setPreguntas(Array.isArray(data)?data:[]);setLoading(false)})();return()=>{a=false}},[codigo,router]);
useEffect(()=>{if(!aplicacion||!avanceKey)return;try{localStorage.setItem(avanceKey,JSON.stringify({indice,respuestas,operado}));}catch{}},[aplicacion,avanceKey,indice,respuestas,operado]);
const visibles=useMemo(()=>preguntas.filter(p=>p.condicional!=='solo_si_operado'||operado===true),[preguntas,operado]);const pregunta=visibles[indice],progreso=visibles.length?Math.round((indice+1)/visibles.length*100):0;const opciones=Array.isArray(pregunta?.opciones)?pregunta.opciones:[];
async function responder(valor){if(enviado)return;let v=valor;if(pregunta.tipo_respuesta==='MULTISELECT_OTRO'){const actual=Array.isArray(respuestas[pregunta.id])?respuestas[pregunta.id]:[];v=actual.includes(valor)?actual.filter(x=>x!==valor):[...actual,valor]}setRespuestas(x=>({...x,[pregunta.id]:v}));if(aplicacion){setGuardando(true);const s=createClient();const{error:e}=await s.rpc('guardar_respuesta_encuesta',{p_sesion_id:sesion,p_pregunta_id:pregunta.id,p_respuesta:v});if(e)setError(e.message);setGuardando(false)}}
function siguiente(){if(pregunta?.obligatoria&&respuestas[pregunta.id]===undefined){setError('Seleccione una respuesta antes de continuar.');return}setError('');if(indice<visibles.length-1)setIndice(i=>i+1)}
async function finalizar(){const faltan=visibles.filter(p=>p.obligatoria&&respuestas[p.id]===undefined);if(faltan.length){setError(`Faltan ${faltan.length} respuestas obligatorias.`);return}if(!aplicacion){setError('La vista administrativa no registra encuestas.');return}if(!window.confirm('¿Enviar definitivamente esta encuesta? Después no podrá modificarse.'))return;setGuardando(true);const s=createClient();const{error:e}=await s.rpc('finalizar_encuesta',{p_sesion_id:sesion});if(e){setError(e.message);setGuardando(false);return}try{localStorage.removeItem(CURSO_KEY);if(avanceKey)localStorage.removeItem(avanceKey);}catch{}setEnviado(true);setGuardando(false)}
if(loading)return <main className="shell"><section className="loginCard"><p>Cargando instrumento…</p></section></main>;if(enviado)return <main className="shell"><section className="loginCard"><div className="badge">ENCUESTAS · OLANCHO</div><h1>Encuesta enviada</h1><p><strong>Folio:</strong> {folio||'—'}</p><p>La encuesta quedó cerrada y bloqueada. Sus respuestas ya no pueden modificarse.</p><a className="button" href="/encuestador">NUEVA ENCUESTA</a></section></main>;if(!pregunta)return <main className="shell"><section className="loginCard"><p>{error||'No se encontraron preguntas.'}</p></section></main>;
const actual=respuestas[pregunta.id];return <main className="shell"><section className="loginCard" style={{maxWidth:'820px'}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>{preguntas[0]?.nombre||'Encuesta'}</h1>{aplicacion&&<p><strong>Folio:</strong> {folio}</p>}{codigo==='HOSPITALIZACION_V1'&&operado===null&&<div style={{border:'2px solid #17634e',padding:'16px',borderRadius:'12px',margin:'16px 0'}}><strong>¿El paciente fue operado durante esta hospitalización?</strong><div style={{display:'flex',gap:'10px',marginTop:'10px'}}><button onClick={()=>setOperado(true)}>SÍ</button><button onClick={()=>setOperado(false)}>NO</button></div><small>Esta selección únicamente determina si se muestran las 4 preguntas quirúrgicas; no agrega una pregunta al instrumento.</small></div>}<p><strong>Pregunta {indice+1} de {visibles.length}</strong> · {progreso}% {guardando?'· Guardando…':''}</p><div style={{height:8,background:'#e5ece9',borderRadius:999}}><div style={{height:'100%',width:`${progreso}%`,background:'#17634e'}}/></div><p style={{color:'#647a74'}}>Dimensión: {pregunta.dimension}</p><h2>{pregunta.texto}</h2><div style={{display:'grid',gap:10}}>{opciones.map(o=>{const sel=Array.isArray(actual)?actual.includes(o):actual===o;return <button key={o} type="button" onClick={()=>responder(o)} style={{background:sel?'#f2b705':'#fff',color:'#173d33',border:sel?'3px solid #8a6500':'2px solid #17634e',textAlign:'left'}}>{sel?'✓ SELECCIONADO · ':''}{o}</button>})}</div>{error&&<p role="alert"><strong>{error}</strong></p>}<div style={{display:'flex',justifyContent:'space-between',gap:12,marginTop:24}}><button disabled={indice===0} onClick={()=>{setError('');setIndice(i=>Math.max(0,i-1))}}>ANTERIOR</button>{indice<visibles.length-1?<button onClick={siguiente}>SIGUIENTE</button>:<button disabled={guardando} onClick={finalizar}>ENVIAR DEFINITIVAMENTE</button>}</div>{aplicacion&&<p style={{fontSize:13,color:'#647a74'}}>Si sale accidentalmente, puede volver al panel del encuestador y seleccionar “CONTINUAR ENCUESTA”.</p>}{!aplicacion&&<p style={{fontSize:13,color:'#647a74'}}>Vista administrativa: permite revisar el instrumento, pero no registra respuestas.</p>}<a className="back" href={aplicacion?'/encuestador':'/encuestas'}>← Volver</a></section></main>}
