'use client';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import Image from 'next/image';

export default function NotificarClinica(){
 const {token}=useParams();const[pin,setPin]=useState(''),[access,setAccess]=useState(null),[conteos,setConteos]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[alerta,setAlerta]=useState({enfermedad_codigo:'',paciente_id:''});
 const inmediatas=useMemo(()=>access?.enfermedades?.filter(x=>x.alerta_inmediata)||[],[access]);
 useEffect(()=>{if(access&&inmediatas.length&&!alerta.enfermedad_codigo)setAlerta(a=>({...a,enfermedad_codigo:inmediatas[0].codigo}))},[access,inmediatas,alerta.enfermedad_codigo]);
 async function ingresar(e){e.preventDefault();setLoading(true);setError('');const res=await fetch('/api/vigilancia/acceso',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,pin})});const data=await res.json();if(!res.ok)setError(data.error);else{const actuales=Object.fromEntries((data.conteos||[]).map(x=>[x.enfermedad_codigo,x.cantidad]));for(const x of data.enfermedades)if(actuales[x.codigo]===undefined)actuales[x.codigo]=0;setConteos(actuales);setAccess(data)}setLoading(false)}
 function setCount(code,value){if(/^\d*$/.test(value))setConteos(c=>({...c,[code]:value===''?'':Number(value)}))}
 async function enviarSemanal(){setLoading(true);setError('');setMessage('');const res=await fetch('/api/vigilancia/notificar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,pin,modo:'SEMANAL',conteos})});const data=await res.json();if(!res.ok)setError(data.error);else setMessage(data.message);setLoading(false)}
 async function enviarAlerta(e){e.preventDefault();setLoading(true);setError('');setMessage('');const res=await fetch('/api/vigilancia/notificar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,pin,modo:'INMEDIATA',...alerta})});const data=await res.json();if(!res.ok)setError(data.error);else{setMessage(data.message);setAlerta(a=>({...a,paciente_id:''}));await ingresar({preventDefault(){}})}setLoading(false)}
 const prior=Object.fromEntries((access?.conteos||[]).map(x=>[x.enfermedad_codigo,x.casos_inmediatos]));
 if(!access)return <main className="vig-shell"><div className="vig-wrap" style={{maxWidth:'520px'}}><section className="vig-card"><div className="vig-brand"><Image src="/viza-logo.svg" alt="Región Olancho" width={68} height={68}/><div><span className="vig-badge">VIGILANCIA OLANCHO</span><h1 style={{fontSize:'30px'}}>Notificación</h1></div></div><p>Ingrese el código de cuatro dígitos asignado a su clínica.</p><form onSubmit={ingresar} className="vig-grid" style={{gridTemplateColumns:'1fr'}}><label className="vig-field">Código de acceso<input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} required/></label>{error&&<p className="vig-error">{error}</p>}<button className="vig-button" disabled={loading}>{loading?'VERIFICANDO…':'INGRESAR'}</button></form></section></div></main>;
 return <main className="vig-shell"><div className="vig-wrap"><header className="vig-header"><div className="vig-brand"><Image src="/viza-logo.svg" alt="Región Olancho" width={68} height={68}/><div><span className="vig-badge">SE {access.periodo.week} · {access.periodo.year}</span><h1>{access.clinica.nombre}</h1><p>{access.clinica.codigo} · {access.clinica.municipio}</p></div></div><button className="vig-button light" onClick={()=>{setAccess(null);setPin('')}}>Salir</button></header>
  <section className="vig-card vig-alert"><h2>Notificación inmediata</h2><p>Use este formulario en cualquier momento para una enfermedad en categoría roja. El caso quedará acumulado en el boletín semanal.</p><form onSubmit={enviarAlerta} className="vig-grid"><label className="vig-field">Enfermedad<select value={alerta.enfermedad_codigo} onChange={e=>setAlerta(a=>({...a,enfermedad_codigo:e.target.value}))}>{inmediatas.map(x=><option key={x.codigo} value={x.codigo}>{x.nombre}{x.requiere_ficha?' · Requiere ficha':''}</option>)}</select></label><label className="vig-field">ID del paciente<input value={alerta.paciente_id} onChange={e=>setAlerta(a=>({...a,paciente_id:e.target.value}))} required/><small>No escriba el nombre del paciente.</small></label><button className="vig-button danger" disabled={loading}>ENVIAR ALERTA</button></form></section>
  {error&&<p className="vig-error" role="alert">{error}</p>}{message&&<p className="vig-ok" role="status">{message}</p>}
  <section className="vig-card"><h2>Boletín semanal obligatorio</h2><p>Todas las casillas comienzan en cero. Los casos inmediatos ya enviados permanecen registrados y no pueden reducirse.</p><div className="vig-disease-grid">{access.enfermedades.map(x=><div className={`vig-disease ${x.alerta_inmediata?'red':''}`} key={x.codigo}><label><span>{x.nombre}</span><input type="number" min={prior[x.codigo]||0} step="1" value={conteos[x.codigo]} onChange={e=>setCount(x.codigo,e.target.value)}/></label>{(prior[x.codigo]||0)>0&&<span className="vig-prior">Ya notificados: {prior[x.codigo]}</span>}{x.requiere_ficha&&<span className="vig-note">Requiere ficha epidemiológica</span>}</div>)}</div><button className="vig-button" disabled={loading||access.boletin?.estado==='CERRADO'} onClick={enviarSemanal}>{loading?'GUARDANDO…':'ENVIAR BOLETÍN SEMANAL'}</button>{access.boletin?.estado==='CERRADO'&&<p className="vig-error">La semana está cerrada.</p>}</section>
 </div></main>;
}
