'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../utils/supabase/client';
const catalogo=[
['Resumen general','Distribución general, número de encuestas y satisfacción global.'],
['Resultados por pregunta y dimensión','Satisfacción por cada pregunta y dimensión del instrumento.'],
['Indicadores de satisfacción','% satisfechos (4+5), muy satisfechos (5), insatisfechos (1+2) y neutral (3).'],
['Tiempo de espera','Resultados del indicador de espera y su relación con satisfacción.'],
['Compra externa','Frecuencia de compra de medicamentos o insumos fuera del establecimiento y cruce con satisfacción.'],
['Intención de regresar','Frecuencia de usuarios que regresarían al establecimiento.'],
['Maltrato o discriminación','Número y porcentaje; se presenta como alerta independiente.'],
['Aspectos negativos','Frecuencia de los aspectos negativos estructurados seleccionados.'],
['Hospitalización','Respuesta oportuna, información al alta, signos de alarma y seguimiento.'],
['ECOR × satisfacción','Comparativo de satisfacción por ECOR.'],['Municipio × satisfacción','Comparativo de satisfacción por municipio.'],['Establecimiento × satisfacción','Comparativo por unidad de salud u hospital.'],['Establecimiento × dimensión','Dimensiones de experiencia por establecimiento.'],['Establecimiento × maltrato','Alertas de maltrato/discriminación por establecimiento.'],['ECOR × dimensión','Comparativo de dimensiones por ECOR.'],['Municipio × dimensión','Comparativo de dimensiones por municipio.'],['Establecimiento × espera','Tiempo de espera por establecimiento.'],['Establecimiento × compra externa','Compra externa por establecimiento.'],['Compra externa × satisfacción','Relación entre compra externa y satisfacción global.'],['Espera × satisfacción','Relación entre espera y satisfacción global.'],['Trato × satisfacción','Relación entre trato y satisfacción global.'],['Comunicación × satisfacción','Relación entre comunicación y satisfacción global.'],['Privacidad × satisfacción','Relación entre privacidad y satisfacción global.'],['Limpieza × satisfacción','Relación entre limpieza y satisfacción global.'],['Maltrato × intención de regresar','Relación entre maltrato y disposición a regresar.'],['Servicio hospitalario × satisfacción','Satisfacción por servicio hospitalario cuando corresponda.'],['Atención médica/enfermería × hospital/servicio','Comparativo de atención médica y de enfermería.'],['Información al alta × servicio','Información al alta por servicio hospitalario.']];
export default function Reportes(){const router=useRouter();const[perfil,setPerfil]=useState(null),[filas,setFilas]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tipo,setTipo]=useState('');
useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data:p}=await s.rpc('obtener_mi_perfil');const x=Array.isArray(p)?p[0]:null;if(!x||!x.activo||!['ADMIN_GENERAL','ADMIN_ENCUESTAS','CONSULTA_ECOR','CONSULTA_MUNICIPAL','CONSULTA_ESTABLECIMIENTO','DIRECTOR_HOSPITALARIO'].includes(x.rol)){router.replace('/panel');return}setPerfil(x);const{data,error:e}=await s.rpc('listar_reportes_encuestas');if(e)setError(e.message);else setFilas(Array.isArray(data)?data:[]);setLoading(false)})()},[router]);
const visibles=useMemo(()=>tipo?filas.filter(x=>x.tipo_encuesta===tipo):filas,[filas,tipo]);
return <main className="shell"><section className="loginCard" style={{maxWidth:'1050px'}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>Reportes</h1><p>Consulta de resultados dentro del alcance autorizado del usuario. ECOR y Municipal únicamente pueden revisar información de los establecimientos que les corresponden.</p>{perfil&&<p><strong>Perfil:</strong> {perfil.rol}</p>}<div style={{border:'1px solid #dce6e2',borderRadius:'12px',padding:'14px',margin:'16px 0'}}><label><strong>Tipo de encuesta</strong><select value={tipo} onChange={e=>setTipo(e.target.value)} style={{width:'100%',padding:'11px',marginTop:'6px'}}><option value="">Todas</option><option value="AMBULATORIA">Atención Ambulatoria</option><option value="HOSPITALIZACION">Hospitalización / Internamiento</option></select></label><p><strong>Encuestas visibles:</strong> {visibles.length}</p></div>{loading&&<p>Cargando…</p>}{error&&<p role="alert"><strong>{error}</strong></p>}<h2>Catálogo de reportes</h2><div style={{display:'grid',gap:'10px'}}>{catalogo.map(([n,d])=><div key={n} style={{border:'1px solid #dce6e2',borderRadius:'10px',padding:'12px'}}><strong>{n}</strong><div style={{fontSize:'14px',marginTop:'4px'}}>{d}</div></div>)}</div><h2 style={{marginTop:'24px'}}>Encuestas disponibles para análisis</h2>{!loading&&!error&&visibles.length===0&&<p>Aún no hay encuestas dentro de este alcance.</p>}{visibles.slice(0,100).map(x=><div key={x.sesion_id} style={{borderBottom:'1px solid #dce6e2',padding:'10px 0'}}><strong>{x.establecimiento_nombre}</strong> · {x.tipo_encuesta}<br/><small>{x.ecor||'—'} · {x.municipio||'—'} · {x.folio} · {x.estado}</small></div>)}<div style={{marginTop:'18px',padding:'12px',background:'#f7faf9',borderRadius:'10px'}}><strong>Semáforo de satisfacción</strong><p>🟢 ≥80% &nbsp; 🟡 70–79.9% &nbsp; 🔴 &lt;70%. El porcentaje se mostrará junto al color. Maltrato/discriminación se mantiene como alerta independiente.</p></div><a className="back" href="/panel">← Volver al panel</a></section></main>}
