'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../utils/supabase/client';

const rolesPermitidos=['ADMIN_GENERAL','ADMIN_ENCUESTAS','CONSULTA_ECOR','CONSULTA_MUNICIPAL','CONSULTA_ESTABLECIMIENTO','DIRECTOR_HOSPITALARIO'];
const likertPos=['Satisfecho','Muy satisfecho'];
const likertNeg=['Muy insatisfecho','Insatisfecho'];
const clean=v=>Array.isArray(v)?v:(v==null?'':String(v));
const sem=p=>p==null?'⚪':Number(p)>=80?'🟢':Number(p)>=70?'🟡':'🔴';
const pct=(n,d)=>d?Math.round((1000*n/d))/10:null;
const uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es'));

export default function Reportes(){
 const router=useRouter();
 const[perfil,setPerfil]=useState(null),[detalle,setDetalle]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const[f,setF]=useState({tipo:'',desde:'',hasta:'',ecor:'',municipio:'',establecimiento:''});
 useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data:p}=await s.rpc('obtener_mi_perfil');const x=Array.isArray(p)?p[0]:null;if(!x||!x.activo||!rolesPermitidos.includes(x.rol)){router.replace('/panel');return}setPerfil(x);const{data,error:e}=await s.rpc('detalle_reportes_encuestas');if(e)setError(e.message);else setDetalle(Array.isArray(data)?data:[]);setLoading(false)})()},[router]);
 const opciones=useMemo(()=>({ecor:uniq(detalle.map(x=>x.ecor)),municipio:uniq(detalle.filter(x=>!f.ecor||x.ecor===f.ecor).map(x=>x.municipio)),establecimiento:uniq(detalle.filter(x=>(!f.ecor||x.ecor===f.ecor)&&(!f.municipio||x.municipio===f.municipio)).map(x=>x.establecimiento_nombre))}),[detalle,f.ecor,f.municipio]);
 const rows=useMemo(()=>detalle.filter(x=>(!f.tipo||x.tipo_encuesta===f.tipo)&&(!f.ecor||x.ecor===f.ecor)&&(!f.municipio||x.municipio===f.municipio)&&(!f.establecimiento||x.establecimiento_nombre===f.establecimiento)&&(!f.desde||String(x.enviada_at||'').slice(0,10)>=f.desde)&&(!f.hasta||String(x.enviada_at||'').slice(0,10)<=f.hasta)),[detalle,f]);
 const sesiones=useMemo(()=>{const m=new Map();rows.forEach(x=>m.set(x.sesion_id,x));return [...m.values()]},[rows]);
 const likert=useMemo(()=>rows.filter(x=>String(x.tipo_respuesta||'').startsWith('LIKERT')),[rows]);
 const sat=likert.filter(x=>likertPos.includes(clean(x.respuesta))).length, muy=likert.filter(x=>clean(x.respuesta)==='Muy satisfecho').length, neg=likert.filter(x=>likertNeg.includes(clean(x.respuesta))).length, neu=likert.filter(x=>clean(x.respuesta)==='Ni satisfecho ni insatisfecho').length;
 const satisf=pct(sat,likert.length);
 const maltrato=rows.filter(x=>x.dimension==='Maltrato o discriminación'&&clean(x.respuesta)==='Sí').length;
 const compra=rows.filter(x=>x.dimension==='Medicamentos e insumos'&&clean(x.respuesta)==='Sí').length;
 const retornoRows=rows.filter(x=>x.dimension==='Intención de retorno'), retornoSi=retornoRows.filter(x=>clean(x.respuesta)==='Sí').length;
 const dims=useMemo(()=>{const m={};likert.forEach(x=>{const k=x.dimension||'Sin dimensión';m[k]??={n:0,pos:0,muy:0,neg:0,neu:0};m[k].n++;const v=clean(x.respuesta);if(likertPos.includes(v))m[k].pos++;if(v==='Muy satisfecho')m[k].muy++;if(likertNeg.includes(v))m[k].neg++;if(v==='Ni satisfecho ni insatisfecho')m[k].neu++});return Object.entries(m).map(([dimension,v])=>({dimension,...v,p: pct(v.pos,v.n)})).sort((a,b)=>(a.p??999)-(b.p??999))},[likert]);
 const preguntas=useMemo(()=>{const m={};rows.forEach(x=>{const k=x.pregunta_id;m[k]??={orden:x.orden,pregunta:x.pregunta,dimension:x.dimension,tipo:x.tipo_respuesta,n:0,vals:{},pos:0,lik:0};const o=m[k];o.n++;const rv=clean(x.respuesta);if(Array.isArray(rv)){rv.forEach(v=>o.vals[v]=(o.vals[v]||0)+1)}else{o.vals[rv]=(o.vals[rv]||0)+1}if(String(x.tipo_respuesta||'').startsWith('LIKERT')){o.lik++;if(likertPos.includes(rv))o.pos++}});return Object.values(m).sort((a,b)=>a.orden-b.orden)},[rows]);
 const cruces=useMemo(()=>{const m={};likert.forEach(x=>{const k=`${x.establecimiento_nombre}|||${x.dimension}`;m[k]??={est:x.establecimiento_nombre,ecor:x.ecor,municipio:x.municipio,dimension:x.dimension,n:0,pos:0};m[k].n++;if(likertPos.includes(clean(x.respuesta)))m[k].pos++});return Object.values(m).map(x=>({...x,p:pct(x.pos,x.n)})).sort((a,b)=>(a.p??999)-(b.p??999))},[likert]);
 const card={border:'1px solid #dce6e2',borderRadius:14,padding:16,background:'#fff'};const sel={width:'100%',padding:10,border:'1px solid #bdcbc6',borderRadius:8};
 function cambio(k,v){setF(q=>({...q,[k]:v,...(k==='ecor'?{municipio:'',establecimiento:''}:{}),...(k==='municipio'?{establecimiento:''}:{})}))}
 function limpiar(){setF({tipo:'',desde:'',hasta:'',ecor:'',municipio:'',establecimiento:''})}
 return <main className="shell"><section className="loginCard" style={{maxWidth:1180}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>Reportes</h1><p>Tablero analítico dentro del alcance territorial autorizado. Los perfiles ECOR, Municipal, Establecimiento y Hospital solo reciben información que les corresponde.</p>{perfil&&<p><strong>Perfil:</strong> {perfil.rol}</p>}
 <div style={{...card,margin:'18px 0'}}><h2 style={{marginTop:0}}>Filtros</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><label>Tipo<select value={f.tipo} onChange={e=>cambio('tipo',e.target.value)} style={sel}><option value="">Todas</option><option value="AMBULATORIA">Atención Ambulatoria</option><option value="HOSPITALIZACION">Hospitalización</option></select></label><label>Desde<input type="date" value={f.desde} onChange={e=>cambio('desde',e.target.value)} style={sel}/></label><label>Hasta<input type="date" value={f.hasta} onChange={e=>cambio('hasta',e.target.value)} style={sel}/></label><label>ECOR<select value={f.ecor} onChange={e=>cambio('ecor',e.target.value)} style={sel}><option value="">Todos</option>{opciones.ecor.map(v=><option key={v}>{v}</option>)}</select></label><label>Municipio<select value={f.municipio} onChange={e=>cambio('municipio',e.target.value)} style={sel}><option value="">Todos</option>{opciones.municipio.map(v=><option key={v}>{v}</option>)}</select></label><label>Establecimiento<select value={f.establecimiento} onChange={e=>cambio('establecimiento',e.target.value)} style={sel}><option value="">Todos</option>{opciones.establecimiento.map(v=><option key={v}>{v}</option>)}</select></label></div><button type="button" onClick={limpiar} style={{marginTop:12,width:'auto'}}>LIMPIAR FILTROS</button></div>
 {loading&&<p>Cargando reportes…</p>}{error&&<p role="alert"><strong>{error}</strong></p>}
 {!loading&&!error&&<><h2>Resumen ejecutivo</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><div style={card}><strong>Encuestas enviadas</strong><div style={{fontSize:30,fontWeight:800}}>{sesiones.length}</div></div><div style={card}><strong>Satisfacción</strong><div style={{fontSize:30,fontWeight:800}}>{sem(satisf)} {satisf==null?'—':`${satisf}%`}</div></div><div style={card}><strong>Muy satisfechos</strong><div style={{fontSize:30,fontWeight:800}}>{pct(muy,likert.length)??'—'}{likert.length?'%':''}</div></div><div style={card}><strong>Insatisfechos</strong><div style={{fontSize:30,fontWeight:800}}>{pct(neg,likert.length)??'—'}{likert.length?'%':''}</div></div><div style={card}><strong>Neutral</strong><div style={{fontSize:30,fontWeight:800}}>{pct(neu,likert.length)??'—'}{likert.length?'%':''}</div></div><div style={{...card,border:maltrato?'2px solid #a83a3a':'1px solid #dce6e2'}}><strong>⚠️ Maltrato/discriminación</strong><div style={{fontSize:30,fontWeight:800}}>{maltrato}</div></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12,marginTop:12}}><div style={card}><strong>Compra externa de medicamento/insumo</strong><div style={{fontSize:26,fontWeight:800}}>{compra}</div></div><div style={card}><strong>Intención de regresar</strong><div style={{fontSize:26,fontWeight:800}}>{pct(retornoSi,retornoRows.length)??'—'}{retornoRows.length?'%':''}</div></div></div>
 <h2 style={{marginTop:28}}>Resultados por dimensión</h2>{dims.length===0?<p>Aún no hay respuestas Likert dentro de los filtros seleccionados.</p>:dims.map(x=><div key={x.dimension} style={{...card,margin:'8px 0',display:'grid',gridTemplateColumns:'minmax(220px,1fr) 120px 1fr',gap:12,alignItems:'center'}}><strong>{x.dimension}</strong><span style={{fontSize:22,fontWeight:800}}>{sem(x.p)} {x.p}%</span><span>{x.pos} satisfechas de {x.n} respuestas · {x.neg} insatisfechas</span></div>)}
 <h2 style={{marginTop:28}}>Resultados por pregunta</h2>{preguntas.length===0?<p>Aún no hay respuestas enviadas.</p>:preguntas.map(q=><details key={q.orden} style={{...card,margin:'8px 0'}}><summary style={{cursor:'pointer',fontWeight:750}}>P{q.orden}. {q.pregunta}</summary><p><strong>Dimensión:</strong> {q.dimension||'—'} · <strong>Respuestas:</strong> {q.n}{q.lik?` · ${sem(pct(q.pos,q.lik))} Satisfacción ${pct(q.pos,q.lik)}%`:''}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{Object.entries(q.vals).sort((a,b)=>b[1]-a[1]).map(([v,n])=><span key={v} style={{border:'1px solid #dce6e2',borderRadius:999,padding:'6px 10px'}}>{v||'Sin respuesta'}: <strong>{n}</strong></span>)}</div></details>)}
 <h2 style={{marginTop:28}}>Cruce establecimiento × dimensión</h2>{cruces.length===0?<p>Sin datos para este cruce.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:8}}>Establecimiento</th><th style={{textAlign:'left',padding:8}}>Municipio</th><th style={{textAlign:'left',padding:8}}>Dimensión</th><th style={{textAlign:'left',padding:8}}>Satisfacción</th><th style={{textAlign:'left',padding:8}}>n</th></tr></thead><tbody>{cruces.map((x,i)=><tr key={`${x.est}-${x.dimension}-${i}`}><td style={{padding:8,borderTop:'1px solid #e5ece9'}}>{x.est}</td><td style={{padding:8,borderTop:'1px solid #e5ece9'}}>{x.municipio}</td><td style={{padding:8,borderTop:'1px solid #e5ece9'}}>{x.dimension}</td><td style={{padding:8,borderTop:'1px solid #e5ece9',fontWeight:750}}>{sem(x.p)} {x.p}%</td><td style={{padding:8,borderTop:'1px solid #e5ece9'}}>{x.n}</td></tr>)}</tbody></table></div>}
 <div style={{marginTop:20,padding:14,background:'#f7faf9',borderRadius:12}}><strong>Semáforo</strong><p>🟢 ≥80% · 🟡 70–79.9% · 🔴 &lt;70%. Maltrato/discriminación permanece como alerta independiente y no se mezcla con el semáforo de satisfacción.</p></div></>}
 <a className="back" href="/panel">← Volver al panel</a></section></main>
}
