'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../utils/supabase/client';
const roles=[['ADMIN_GENERAL','Administrador General'],['ADMIN_ENCUESTAS','Administrador de Encuestas'],['JEFE_ENCUESTADORES','Jefe de Encuestadores'],['CONSULTA_ECOR','Consulta ECOR'],['CONSULTA_MUNICIPAL','Consulta Municipal'],['CONSULTA_ESTABLECIMIENTO','Consulta Establecimiento'],['DIRECTOR_HOSPITALARIO','Director Hospitalario']];
const nombresRol=Object.fromEntries([...roles,['ENCUESTADOR','Encuestador']]);
const vacio={nombre:'',email:'',telefono:'',password:'',confirmar_password:'',rol:'ADMIN_ENCUESTAS',alcance_ecor:'',alcance_municipio:'',alcance_establecimiento_codigo:'',alcance_establecimiento_nombre:'',alcance_hospital_nombre:''};
export default function UsuariosPage(){const router=useRouter();const[loading,setLoading]=useState(true),[error,setError]=useState(''),[ok,setOk]=useState(''),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState(''),[form,setForm]=useState(vacio),[usuarios,setUsuarios]=useState([]),[ecor,setEcor]=useState([]),[municipios,setMunicipios]=useState([]),[establecimientos,setEstablecimientos]=useState([]),[hospitales,setHospitales]=useState([]);
async function cargarUsuarios(){const s=createClient();const{data,error:e}=await s.rpc('listar_usuarios_admin');if(e){setError(e.message);return}setUsuarios(Array.isArray(data)?data:[])}
useEffect(()=>{let a=true;(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data}=await s.rpc('obtener_mi_perfil');const p=Array.isArray(data)?data[0]:null;if(!p||p.rol!=='ADMIN_GENERAL'||!p.activo){router.replace('/panel');return}const[er,mr,hr]=await Promise.all([s.rpc('listar_ecor_encuestas'),s.rpc('listar_municipios_encuestas'),s.rpc('listar_hospitales_encuestas')]);if(er.error||mr.error||hr.error)setError(er.error?.message||mr.error?.message||hr.error?.message);else{setEcor((er.data||[]).map(x=>x.ecor));setMunicipios((mr.data||[]).map(x=>x.municipio));setHospitales(hr.data||[])}await cargarUsuarios();if(a)setLoading(false)})();return()=>{a=false}},[router]);
function campo(c,v){setForm(f=>({...f,[c]:v}))}
function cambiarRol(v){setForm(f=>({...vacio,nombre:f.nombre,email:f.email,telefono:f.telefono,password:f.password,confirmar_password:f.confirmar_password,rol:v}));setEstablecimientos([])}
async function elegirMunicipio(v,paraES=false){setForm(f=>({...f,alcance_municipio:v,alcance_establecimiento_codigo:'',alcance_establecimiento_nombre:''}));setEstablecimientos([]);if(paraES&&v){const s=createClient();const{data,error:e}=await s.rpc('listar_establecimientos_municipio_encuestas',{p_municipio:v});if(e)setError(e.message);else setEstablecimientos((data||[]).filter(x=>!x.hospital))}}
function elegirES(c){const x=establecimientos.find(e=>e.codigo===c);setForm(f=>({...f,alcance_establecimiento_codigo:c,alcance_establecimiento_nombre:x?.nombre||''}))}
async function crear(e){e.preventDefault();setError('');setOk('');if(form.password.length<8){setError('La contraseña debe tener al menos 8 caracteres.');return}if(form.password!==form.confirmar_password){setError('Las contraseñas no coinciden.');return}setSaving(true);const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session?.access_token){setError('La sesión no es válida.');setSaving(false);return}const res=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/crear-usuario-perfil`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(form)});const r=await res.json().catch(()=>({}));if(!res.ok||!r.ok)setError(r.error||'No fue posible crear el usuario.');else{setOk(`Usuario creado correctamente. El usuario de acceso es ${form.email}.`);setForm(vacio);setEstablecimientos([]);await cargarUsuarios()}setSaving(false)}
async function eliminar(u){setError('');setOk('');const nombre=u.nombre||u.email||'este usuario';if(!window.confirm(`¿Eliminar a ${nombre}?\n\nEsta acción elimina su acceso a la plataforma y no se puede deshacer.`))return;setDeletingId(u.id);try{const s=createClient();const{data:{session}}=await s.auth.getSession();if(!session?.access_token)throw new Error('La sesión no es válida.');const res=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/eliminar-usuario-perfil`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({usuario_id:u.id})});const r=await res.json().catch(()=>({}));if(!res.ok||!r.ok)throw new Error(r.error||'No fue posible eliminar el usuario.');setOk(`Usuario ${nombre} eliminado correctamente.`);await cargarUsuarios()}catch(e){setError(e instanceof Error?e.message:'No fue posible eliminar el usuario.')}finally{setDeletingId('')}}
if(loading)return <main className="shell"><section className="loginCard"><p>Preparando gestión de usuarios…</p></section></main>;
const sel={width:'100%',padding:'12px',border:'1px solid #bdcbc6',borderRadius:'9px'};const esE=form.rol==='CONSULTA_ECOR',esM=form.rol==='CONSULTA_MUNICIPAL',esES=form.rol==='CONSULTA_ESTABLECIMIENTO',esH=form.rol==='DIRECTOR_HOSPITALARIO';
return <main className="shell"><section className="loginCard" style={{maxWidth:'900px'}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>Gestionar usuarios</h1><p>Creación de perfiles administrativos, de supervisión y de consulta.</p><form onSubmit={crear} style={{display:'grid',gap:'14px'}}><label><strong>Nombre completo</strong><input required value={form.nombre} onChange={e=>campo('nombre',e.target.value)} style={{width:'100%'}}/></label><label><strong>Correo electrónico / Usuario</strong><input required type="email" value={form.email} onChange={e=>campo('email',e.target.value)} style={{width:'100%'}}/></label><label><strong>Número de teléfono</strong><input required type="tel" value={form.telefono} onChange={e=>campo('telefono',e.target.value)} style={{width:'100%'}}/></label><label><strong>Contraseña</strong><input required type="password" minLength={8} value={form.password} onChange={e=>campo('password',e.target.value)} style={{width:'100%'}}/><small>Mínimo 8 caracteres.</small></label><label><strong>Verificar contraseña</strong><input required type="password" minLength={8} value={form.confirmar_password} onChange={e=>campo('confirmar_password',e.target.value)} style={{width:'100%'}}/></label><label><strong>Perfil</strong><select value={form.rol} onChange={e=>cambiarRol(e.target.value)} style={sel}>{roles.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
{esE&&<label><strong>ECOR asignado</strong><select required value={form.alcance_ecor} onChange={e=>campo('alcance_ecor',e.target.value)} style={sel}><option value="">Seleccione ECOR</option>{ecor.map(x=><option key={x}>{x}</option>)}</select></label>}
{esM&&<label><strong>Municipio asignado</strong><select required value={form.alcance_municipio} onChange={e=>elegirMunicipio(e.target.value)} style={sel}><option value="">Seleccione municipio</option>{municipios.map(x=><option key={x}>{x}</option>)}</select></label>}
{esES&&<><label><strong>Municipio</strong><select required value={form.alcance_municipio} onChange={e=>elegirMunicipio(e.target.value,true)} style={sel}><option value="">Seleccione municipio</option>{municipios.map(x=><option key={x}>{x}</option>)}</select></label><label><strong>Establecimiento asignado</strong><select required disabled={!form.alcance_municipio} value={form.alcance_establecimiento_codigo} onChange={e=>elegirES(e.target.value)} style={sel}><option value="">Seleccione establecimiento</option>{establecimientos.map(x=><option key={x.codigo} value={x.codigo}>{x.nombre} · RUPS {x.codigo}</option>)}</select></label></>}
{esH&&<label><strong>Hospital asignado</strong><select required value={form.alcance_hospital_nombre} onChange={e=>campo('alcance_hospital_nombre',e.target.value)} style={sel}><option value="">Seleccione hospital</option>{hospitales.map(x=><option key={x.codigo} value={x.nombre}>{x.nombre}</option>)}</select></label>}
<button disabled={saving}>{saving?'CREANDO…':'CREAR USUARIO'}</button></form>{error&&<p role="alert"><strong>{error}</strong></p>}{ok&&<p role="status"><strong>{ok}</strong></p>}<div style={{marginTop:'30px',borderTop:'1px solid #dce6e2'}}><h2>Usuarios creados</h2>{usuarios.map(u=><div key={u.id} style={{border:'1px solid #dce6e2',borderRadius:'12px',padding:'14px',margin:'10px 0'}}><strong>{u.nombre||'Sin nombre'}</strong><p>{u.email||'—'} · {nombresRol[u.rol]||u.rol} · {u.activo?'Activo':'Inactivo'}</p>{u.alcance_ecor&&<p>ECOR: {u.alcance_ecor}</p>}{u.alcance_municipio&&<p>Municipio: {u.alcance_municipio}</p>}{u.alcance_establecimiento_nombre&&<p>Establecimiento: {u.alcance_establecimiento_nombre} · {u.alcance_establecimiento_codigo}</p>}{u.alcance_hospital_nombre&&<p>Hospital: {u.alcance_hospital_nombre}</p>}{u.rol!=='ADMIN_GENERAL'&&<button type="button" onClick={()=>eliminar(u)} disabled={!!deletingId} style={{marginTop:'8px',background:'#8f1d1d'}}>{deletingId===u.id?'ELIMINANDO…':'ELIMINAR USUARIO'}</button>}</div>)}</div><a className="back" href="/panel">← Volver al panel</a></section></main>}
