'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../../utils/supabase/client';

const roles=['ADMIN_GENERAL','ADMIN_ENCUESTAS','CONSULTA_ECOR','CONSULTA_MUNICIPAL','CONSULTA_ESTABLECIMIENTO','DIRECTOR_HOSPITALARIO'];
const POS=['Satisfecho','Muy satisfecho'];
const NEG=['Muy insatisfecho','Insatisfecho'];
const NEU='Ni satisfecho ni insatisfecho';
const pct=(n,d)=>d?Math.round((n*1000/d))/10:null;
const uniq=a=>[...new Set(a.filter(Boolean).map(String))].sort((a,b)=>a.localeCompare(b,'es'));
const val=v=>Array.isArray(v)?v.join(' | '):(v==null?'':String(v));
const fmt=p=>p==null?'—':`${p}%`;
const sem=p=>p==null?'⚪':p>=80?'🟢':p>=70?'🟡':'🔴';

export default function ReporteEjecutivo(){
 const router=useRouter();
 const[detalle,setDetalle]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[f,setF]=useState({tipo:'',desde:'',hasta:'',ecor:'',municipio:'',establecimiento:''});
 useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data:p}=await s.rpc('obtener_mi_perfil');const x=Array.isArray(p)?p[0]:null;if(!x||!x.activo||!roles.includes(x.rol)){router.replace('/panel');return}const{data,error:e}=await s.rpc('detalle_reportes_encuestas');if(e)setError(e.message);else setDetalle(Array.isArray(data)?data:[]);setLoading(false)})()},[router]);
 const opciones=useMemo(()=>({ecor:uniq(detalle.map(x=>x.ecor)),municipio:uniq(detalle.filter(x=>!f.ecor||x.ecor===f.ecor).map(x=>x.municipio)),establecimiento:uniq(detalle.filter(x=>(!f.ecor||x.ecor===f.ecor)&&(!f.municipio||x.municipio===f.municipio)).map(x=>x.establecimiento_nombre))}),[detalle,f.ecor,f.municipio]);
 const rows=useMemo(()=>detalle.filter(x=>(!f.tipo||x.tipo_encuesta===f.tipo)&&(!f.ecor||x.ecor===f.ecor)&&(!f.municipio||x.municipio===f.municipio)&&(!f.establecimiento||x.establecimiento_nombre===f.establecimiento)&&(!f.desde||String(x.enviada_at||'').slice(0,10)>=f.desde)&&(!f.hasta||String(x.enviada_at||'').slice(0,10)<=f.hasta)),[detalle,f]);
 const sesiones=useMemo(()=>{const m=new Map();rows.forEach(x=>m.set(x.sesion_id,x));return [...m.values()]},[rows]);
 const likert=useMemo(()=>rows.filter(x=>String(x.tipo_respuesta||'').startsWith('LIKERT')),[rows]);
 const totalSat=likert.filter(x=>POS.includes(val(x.respuesta))).length,totalNeg=likert.filter(x=>NEG.includes(val(x.respuesta))).length,totalNeu=likert.filter(x=>val(x.respuesta)===NEU).length;
 const satisf=pct(totalSat,likert.length);
 const amb=sesiones.filter(x=>x.tipo_encuesta==='AMBULATORIA').length,hosp=sesiones.filter(x=>x.tipo_encuesta==='HOSPITALIZACION').length;
 const establecimientos=uniq(sesiones.map(x=>x.establecimiento_nombre)).length;
 function agrupar(campo){const m={};likert.forEach(x=>{const k=x[campo]||'Sin dato';m[k]??={nombre:k,n:0,pos:0,neg:0,neu:0};const o=m[k],v=val(x.respuesta);o.n++;if(POS.includes(v))o.pos++;if(NEG.includes(v))o.neg++;if(v===NEU)o.neu++});return Object.values(m).map(x=>({...x,p:pct(x.pos,x.n),pn:pct(x.neg,x.n),pneu:pct(x.neu,x.n)})).sort((a,b)=>(b.p??-1)-(a.p??-1))}
 const porDimension=useMemo(()=>agrupar('dimension'),[likert]);
 const porTipo=useMemo(()=>agrupar('tipo_encuesta'),[likert]);
 const porEst=useMemo(()=>agrupar('establecimiento_nombre'),[likert]);
 const porEcor=useMemo(()=>agrupar('ecor'),[likert]);
 const alertas=useMemo(()=>{const out=[];const dims=[...porDimension].sort((a,b)=>(a.p??999)-(b.p??999));dims.slice(0,5).forEach(x=>out.push({tipo:'Prioridad',texto:`${x.nombre}: ${fmt(x.p)} de satisfacción (${x.pos}/${x.n}); ${fmt(x.pn)} desfavorable.`}));const mejor=[...porDimension].sort((a,b)=>(b.p??-1)-(a.p??-1))[0];if(mejor)out.push({tipo:'Fortaleza',texto:`Mejor dimensión: ${mejor.nombre}, ${fmt(mejor.p)} de satisfacción.`});const mal=rows.filter(x=>x.dimension==='Maltrato o discriminación'&&val(x.respuesta)==='Sí').length;const maln=rows.filter(x=>x.dimension==='Maltrato o discriminación').length;if(mal)out.unshift({tipo:'Alerta',texto:`Maltrato/discriminación: ${mal}/${maln} respuestas afirmativas (${fmt(pct(mal,maln))}).`});const compra=rows.filter(x=>x.dimension==='Medicamentos e insumos'&&val(x.respuesta)==='Sí').length;const compran=rows.filter(x=>x.dimension==='Medicamentos e insumos').length;if(compra)out.push({tipo:'Prioridad',texto:`Compra externa de medicamentos/insumos: ${compra}/${compran} (${fmt(pct(compra,compran))}).`});return out},[porDimension,rows]);
 const card={border:'1px solid #dce6e2',borderRadius:14,padding:16,background:'#fff'};
 const sel={width:'100%',padding:10,border:'1px solid #bdcbc6',borderRadius:8};
 const barra=(p)=>Math.max(0,Math.min(100,p||0));
 function Barra({nombre,p,n,neg}){return <div style={{margin:'12px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{nombre}</strong><strong>{sem(p)} {fmt(p)}</strong></div><div style={{height:18,background:'#edf2f0',borderRadius:999,overflow:'hidden',marginTop:6}}><div style={{height:'100%',width:`${barra(p)}%`,background:p>=80?'#2f7d62':p>=70?'#d5a11e':'#b84a4a'}}/></div><small>{n} respuestas Likert{neg!=null?` · ${fmt(neg)} desfavorables`:''}</small></div>}
 function TablaRanking({titulo,data}){return <div style={{...card,marginTop:16}}><h3 style={{marginTop:0}}>{titulo}</h3>{data.length===0?<p>Sin datos.</p>:data.map(x=><Barra key={x.nombre} nombre={x.nombre} p={x.p} n={x.n} neg={x.pn}/>)}</div>}
 return <main className="shell"><section className="loginCard" style={{maxWidth:1220}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>Reporte ejecutivo</h1><p>Lectura rápida para toma de decisiones. Los gráficos usan porcentajes de satisfacción Likert y siempre muestran su base de respuestas.</p>
 <div style={{...card,margin:'18px 0'}}><h2 style={{marginTop:0}}>Filtros</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><label>Tipo<select style={sel} value={f.tipo} onChange={e=>setF(x=>({...x,tipo:e.target.value}))}><option value="">Todas</option><option value="AMBULATORIA">Ambulatoria</option><option value="HOSPITALIZACION">Hospitalización</option></select></label><label>Desde<input style={sel} type="date" value={f.desde} onChange={e=>setF(x=>({...x,desde:e.target.value}))}/></label><label>Hasta<input style={sel} type="date" value={f.hasta} onChange={e=>setF(x=>({...x,hasta:e.target.value}))}/></label><label>ECOR<select style={sel} value={f.ecor} onChange={e=>setF(x=>({...x,ecor:e.target.value,municipio:'',establecimiento:''}))}><option value="">Todos</option>{opciones.ecor.map(v=><option key={v}>{v}</option>)}</select></label><label>Municipio<select style={sel} value={f.municipio} onChange={e=>setF(x=>({...x,municipio:e.target.value,establecimiento:''}))}><option value="">Todos</option>{opciones.municipio.map(v=><option key={v}>{v}</option>)}</select></label><label>Establecimiento<select style={sel} value={f.establecimiento} onChange={e=>setF(x=>({...x,establecimiento:e.target.value}))}><option value="">Todos</option>{opciones.establecimiento.map(v=><option key={v}>{v}</option>)}</select></label></div><button type="button" onClick={()=>setF({tipo:'',desde:'',hasta:'',ecor:'',municipio:'',establecimiento:''})}>LIMPIAR FILTROS</button></div>
 {loading&&<p>Cargando…</p>}{error&&<p role="alert"><strong>{error}</strong></p>}{!loading&&!error&&<>
 <h2>1. Panorama en 30 segundos</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><div style={card}><strong>Encuestas válidas</strong><div style={{fontSize:32,fontWeight:800}}>{sesiones.length}</div></div><div style={card}><strong>Ambulatorias</strong><div style={{fontSize:32,fontWeight:800}}>{amb}</div></div><div style={card}><strong>Hospitalización</strong><div style={{fontSize:32,fontWeight:800}}>{hosp}</div></div><div style={card}><strong>Establecimientos</strong><div style={{fontSize:32,fontWeight:800}}>{establecimientos}</div></div><div style={card}><strong>Satisfacción global</strong><div style={{fontSize:32,fontWeight:800}}>{sem(satisf)} {fmt(satisf)}</div><small>{totalSat}/{likert.length}</small></div><div style={card}><strong>Desfavorable</strong><div style={{fontSize:32,fontWeight:800}}>{fmt(pct(totalNeg,likert.length))}</div><small>{totalNeg}/{likert.length}</small></div></div>
 <div style={{...card,marginTop:16}}><h3 style={{marginTop:0}}>Composición global de respuestas</h3><div style={{display:'flex',height:32,borderRadius:999,overflow:'hidden',background:'#edf2f0'}}>{likert.length>0&&<><div title="Satisfechas" style={{width:`${pct(totalSat,likert.length)}%`,background:'#2f7d62'}}/><div title="Neutrales" style={{width:`${pct(totalNeu,likert.length)}%`,background:'#d5a11e'}}/><div title="Insatisfechas" style={{width:`${pct(totalNeg,likert.length)}%`,background:'#b84a4a'}}/></>}</div><p><strong>Satisfechas:</strong> {fmt(pct(totalSat,likert.length))} · <strong>Neutrales:</strong> {fmt(pct(totalNeu,likert.length))} · <strong>Desfavorables:</strong> {fmt(pct(totalNeg,likert.length))}</p></div>
 <h2 style={{marginTop:28}}>2. Hallazgos prioritarios</h2><div style={card}>{alertas.length===0?<p>Sin datos suficientes.</p>:alertas.map((h,i)=><div key={i} style={{padding:'10px 0',borderBottom:i<alertas.length-1?'1px solid #e5ece9':'none'}}><strong>{h.tipo}:</strong> {h.texto}</div>)}</div>
 <h2 style={{marginTop:28}}>3. Dimensiones: dónde actuar primero</h2><TablaRanking titulo="Dimensiones ordenadas por satisfacción" data={[...porDimension].sort((a,b)=>(a.p??999)-(b.p??999))}/>
 <h2 style={{marginTop:28}}>4. Cruces con sentido</h2><p>Se priorizan comparaciones que ayudan a localizar diferencias operativas; no implican causalidad.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:14}}><TablaRanking titulo="Ambulatoria vs Hospitalización" data={porTipo}/><TablaRanking titulo="Establecimientos" data={porEst}/><TablaRanking titulo="ECOR" data={porEcor}/></div>
 <h2 style={{marginTop:28}}>5. Lectura recomendada</h2><div style={card}><p><strong>Prioridad inmediata:</strong> revisar primero dimensiones y establecimientos en rojo (&lt;70%), especialmente si además tienen una proporción desfavorable alta.</p><p><strong>Comparación útil:</strong> una diferencia grande entre Ambulatoria y Hospitalización orienta dónde profundizar el análisis.</p><p style={{marginBottom:0}}><strong>Regla de interpretación:</strong> leer siempre porcentaje junto con el número de respuestas; una diferencia con n pequeño puede ser inestable.</p></div>
 </>}
 <a className="back" href="/reportes">← Volver al reporte detallado</a></section></main>
}
