'use client';
import { useEffect,useState } from 'react';
import { createClient } from '../../../utils/supabase/client';

async function token(){const s=createClient();const{data:{session}}=await s.auth.getSession();return session?.access_token||''}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
export default function ReportesVigilancia(){
 const[anio,setAnio]=useState(new Date().getFullYear()),[semana,setSemana]=useState(''),[enfermedad,setEnfermedad]=useState(''),[paciente,setPaciente]=useState(''),[data,setData]=useState({enfermedades:[],boletines:[],eventos:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const t=await token();const q=new URLSearchParams({anio:String(anio),semana:String(semana),enfermedad,paciente});const r=await fetch(`/api/vigilancia/reportes?${q}`,{headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);setAnio(d.anio);setSemana(d.semana);setData(d)}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 function download(){const lines=[['Año','Semana','Municipio','Código clínica','Clínica','Estado','Enfermedad','Cantidad','Casos inmediatos'].map(csvCell).join(',')];for(const b of data.boletines)for(const c of b.conteos)lines.push([b.anio,b.semana_epidemiologica,b.clinica?.municipio,b.clinica?.codigo,b.clinica?.nombre,b.estado,c.enfermedad_nombre,c.cantidad,c.casos_inmediatos].map(csvCell).join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Vigilancia_Olancho_SE${semana}_${anio}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const total=data.boletines.flatMap(b=>b.conteos).reduce((s,x)=>s+Number(x.cantidad||0),0);
 return <main className="vig-shell"><div className="vig-wrap"><div className="vig-header"><div><span className="vig-badge">BOLETINES</span><h1>Consulta y descarga</h1><p>Búsqueda por enfermedad, semana epidemiológica e ID de paciente.</p></div><a className="vig-button light" href="/vigilancia/panel">Volver</a></div><section className="vig-card"><div className="vig-grid"><label className="vig-field">Año<input type="number" value={anio} onChange={e=>setAnio(e.target.value)}/></label><label className="vig-field">Semana<input type="number" min="1" max="53" value={semana} onChange={e=>setSemana(e.target.value)}/></label><label className="vig-field">Enfermedad<select value={enfermedad} onChange={e=>setEnfermedad(e.target.value)}><option value="">Todas</option>{data.enfermedades.map(x=><option key={x.codigo} value={x.codigo}>{x.nombre}</option>)}</select></label><label className="vig-field">ID de paciente<input value={paciente} onChange={e=>setPaciente(e.target.value)}/></label></div><div className="vig-actions"><button className="vig-button" onClick={load}>BUSCAR</button><button className="vig-button secondary" onClick={download}>DESCARGAR CSV</button><a className="vig-button light" href="/vigilancia/fichas">FICHAS OFICIALES</a></div></section>{error&&<p className="vig-error">{error}</p>}<section className="vig-grid"><div className="vig-stat">Boletines<strong>{data.boletines.length}</strong></div><div className="vig-stat">Casos registrados<strong>{total}</strong></div><div className="vig-stat">Alertas inmediatas<strong>{data.eventos.length}</strong></div></section>
 {loading?<section className="vig-card">Consultando…</section>:<><section className="vig-card"><h2>Boletines</h2><div className="vig-table-wrap"><table className="vig-table"><thead><tr><th>Clínica</th><th>Estado</th><th>Enfermedad</th><th>Cantidad</th><th>Inmediatos</th><th>Detalle</th></tr></thead><tbody>{data.boletines.flatMap(b=>b.conteos.filter(c=>c.cantidad>0).map(c=><tr key={`${b.id}-${c.enfermedad_codigo}`}><td>{b.clinica?.nombre}<br/>{b.clinica?.municipio}</td><td>{b.estado}</td><td>{c.enfermedad_nombre}</td><td>{c.cantidad}</td><td>{c.casos_inmediatos}</td><td><a href={`/vigilancia/boletines/${b.id}`}>Abrir</a></td></tr>))}</tbody></table></div></section><section className="vig-card"><h2>Alertas inmediatas / búsqueda nominal</h2><div className="vig-table-wrap"><table className="vig-table"><thead><tr><th>Fecha</th><th>Clínica</th><th>Enfermedad</th><th>ID paciente</th></tr></thead><tbody>{data.eventos.map(e=><tr key={e.id}><td>{new Date(e.notificado_at).toLocaleString('es-HN')}</td><td>{e.clinica?.nombre}</td><td>{e.enfermedad_nombre}</td><td>{e.paciente_id}</td></tr>)}</tbody></table></div></section></>}
 </div></main>
}
