'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '../../utils/supabase/client';

export default function Panel() {
  const router = useRouter();
  const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [role, setRole] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [resetMessage, setResetMessage] = useState(''); const [resetting, setResetting] = useState(false);
  useEffect(()=>{let active=true;(async()=>{const supabase=createClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user){router.replace('/login');return}const{data,error:profileError}=await supabase.rpc('obtener_mi_perfil');const profile=Array.isArray(data)?data[0]:null;if(!active)return;setEmail(user.email||'');if(profileError){setError('No fue posible leer el perfil del usuario.');setRole('SIN PERFIL')}else if(!profile){setError('El usuario está autenticado, pero no tiene un perfil asignado.');setRole('SIN PERFIL')}else if(!profile.activo){setError('Este usuario se encuentra inactivo.');setName(profile.nombre||'');setRole(profile.rol||'SIN PERFIL')}else{setName(profile.nombre||'');setRole(profile.rol||'SIN PERFIL')}setLoading(false)})();return()=>{active=false}},[router]);
  async function signOut(){const supabase=createClient();await supabase.auth.signOut();router.replace('/login');router.refresh()}
  async function resetTests(){if(role!=='ADMIN_GENERAL'||resetting)return;if(!window.confirm('RESETEO DE PRUEBAS\n\nEsta acción eliminará las sesiones y respuestas de prueba, por lo que los reportes quedarán en cero. Conserva usuarios, perfiles, catálogos, instrumentos y designaciones. ¿Desea continuar?'))return;if(!window.confirm('Confirme nuevamente el RESETEO DE PRUEBAS. Esta acción no se puede deshacer.'))return;setResetting(true);setResetMessage('');const supabase=createClient();const{data,error:resetError}=await supabase.rpc('resetear_pruebas_encuestas');if(resetError){setResetMessage(`No fue posible completar el reseteo: ${resetError.message}`);setResetting(false);return}try{window.localStorage.clear();window.sessionStorage.clear()}catch{}const r=Array.isArray(data)?data[0]:null;setResetMessage(`Entorno de prueba reiniciado. ${r?.sesiones_eliminadas??0} sesiones y ${r?.respuestas_eliminadas??0} respuestas eliminadas. Los reportes quedaron en cero.`);setResetting(false)}
  if(loading)return <main className="shell"><section className="loginCard"><p>Verificando acceso…</p></section></main>;
  const esAplicador=role==='ENCUESTADOR'||role==='JEFE_ENCUESTADORES';const esConsulta=['CONSULTA_ECOR','CONSULTA_MUNICIPAL','CONSULTA_ESTABLECIMIENTO','DIRECTOR_HOSPITALARIO'].includes(role);const panelBtn={padding:'9px 16px',fontSize:'13px',borderRadius:'8px',marginTop:'6px'};const panelGrid={display:'grid',gap:'6px'};const listado=<a className="button" style={panelBtn} href="/listado-encuestas">ENCUESTAS REALIZADAS</a>;
  return <main className="shell"><section className="loginCard"><div className="badge">ENCUESTAS · OLANCHO</div><h1>Panel</h1><p>Sesión activa.</p>{name&&<p><strong>Nombre:</strong> {name}</p>}<p><strong>Usuario:</strong> {email}</p><p><strong>Perfil:</strong> {role}</p>{error&&<p role="alert">{error}</p>}
  {!error&&role==='ADMIN_GENERAL'&&<div style={panelGrid}><a className="button" style={panelBtn} href="/encuestas">VER ENCUESTAS</a>{listado}<a className="button" style={panelBtn} href="/reportes">REPORTES</a><a className="button" style={panelBtn} href="/usuarios">GESTIONAR USUARIOS</a><a className="button" style={panelBtn} href="/encuestadores">GESTIONAR ENCUESTADORES</a><a className="button" style={panelBtn} href="/designaciones">DESIGNAR ENCUESTADORES</a><a className="button" style={panelBtn} href="/roles">TIPOS DE USUARIO</a></div>}
  {!error&&role==='ADMIN_ENCUESTAS'&&<div style={panelGrid}><a className="button" style={panelBtn} href="/encuestas">VER ENCUESTAS</a>{listado}<a className="button" style={panelBtn} href="/reportes">REPORTES</a><a className="button" style={panelBtn} href="/encuestadores">GESTIONAR ENCUESTADORES</a><a className="button" style={panelBtn} href="/designaciones">DESIGNAR ENCUESTADORES</a></div>}
  {!error&&role==='JEFE_ENCUESTADORES'&&<a className="button" style={panelBtn} href="/jefe-encuestadores">PANEL JEFE</a>}{!error&&role==='ENCUESTADOR'&&<a className="button" style={panelBtn} href="/encuestador">APLICAR ENCUESTAS</a>}
  {!error&&esConsulta&&<div style={panelGrid}>{listado}<a className="button" style={panelBtn} href="/reportes">REPORTES</a><a className="button" style={panelBtn} href="/consulta">VER RESULTADOS</a></div>}
  {!error&&!esAplicador&&!esConsulta&&!['ADMIN_GENERAL','ADMIN_ENCUESTAS'].includes(role)&&<a className="button" style={panelBtn} href="/encuestas">VER ENCUESTAS</a>}
  {!error&&<a className="button" href="/actualizar-contrasena" style={{...panelBtn,marginTop:'10px'}}>CAMBIAR CONTRASEÑA</a>}
  {!error&&role==='ADMIN_GENERAL'&&<div style={{marginTop:'14px',paddingTop:'14px',borderTop:'1px solid #dce6e2'}}><button type="button" disabled={resetting} onClick={resetTests} style={{background:'#8f2f2f',padding:'9px 16px',fontSize:'13px'}}>{resetting?'RESETEANDO…':'RESETEAR PRUEBAS'}</button><p style={{fontSize:'13px',color:'#647a74',marginTop:'8px'}}>Elimina sesiones y respuestas de prueba. Conserva usuarios, perfiles, catálogos, instrumentos y designaciones.</p>{resetMessage&&<p role="status"><strong>{resetMessage}</strong></p>}</div>}
  <button type="button" onClick={signOut} style={{padding:'9px 16px',fontSize:'13px',marginTop:'10px'}}>CERRAR SESIÓN</button></section></main>;
}
