'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../utils/supabase/client';
const roles=['ADMIN_GENERAL','ADMIN_ENCUESTAS','CONSULTA_ECOR','CONSULTA_MUNICIPAL','CONSULTA_ESTABLECIMIENTO','DIRECTOR_HOSPITALARIO'];
const val=v=>Array.isArray(v)?v.join(' | '):(v==null?'':String(v));
export default function ListadoEncuestas(){
 const router=useRouter();const[lista,setLista]=useState([]),[detalle,setDetalle]=useState([]),[sel,setSel]=useState(null),[q,setQ]=useState(''),[estado,setEstado]=useState('ENVIADA'),[encuestador,setEncuestador]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data:p}=await s.rpc('obtener_mi_perfil');const perfil=Array.isArray(p)?p[0]:null;if(!perfil||!perfil.activo||!roles.includes(perfil.rol)){router.replace('/panel');return}const[{data:l,error:le},{data:d,error:de}]=await Promise.all([s.rpc('listar_reportes_encuestas'),s.rpc('detalle_reportes_encuestas')]);if(le||de)setError(le?.message||de?.message);else{setLista(Array.isArray(l)?l:[]);setDetalle(Array.isArray(d)?d:[])}setLoading(false)})()},[router]);
 const finalizadas=useMemo(()=>lista.filter(x=>x.estado==='ENVIADA'),[lista]);
 const porEncuestador=useMemo(()=>{const m=new Map();finalizadas.forEach(x=>{const id=x.encuestador_id||'Sin identificador';if(!m.has(id))m.set(id,{id,total:0,folios:[]});const o=m.get(id);o.total++;o.folios.push(x.folio)});return [...m.values()].sort((a,b)=>b.total-a.total||String(a.id).localeCompare(String(b.id),'es'))},[finalizadas]);
 const filtrada=useMemo(()=>lista.filter(x=>(!estado||x.estado===estado)&&(!encuestador||x.encuestador_id===encuestador)&&(!q||[x.folio,x.establecimiento_nombre,x.municipio,x.ecor,x.encuestador_id].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase())))),[lista,q,estado,encuestador]);
 const respuestas=useMemo(()=>sel?detalle.filter(x=>x.sesion_id===sel.sesion_id).sort((a,b)=>(a.orden||0)-(b.orden||0)):[],[detalle,sel]);
 const st={padding:'8px',borderTop:'1px solid #e5ece9',verticalAlign:'top'};
 function verEncuestador(id){setEncuestador(id);setEstado('ENVIADA');setQ('');setSel(null);setTimeout(()=>document.getElementById('listado-encuestas')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}
 if(loading)return <main className="shell"><section className="loginCard"><p>Cargando encuestas…</p></section></main>;
 return <main className="shell"><section className="loginCard" style={{maxWidth:1180}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>Encuestas realizadas</h1><p>Listado para localizar y revisar cada encuesta por su código (folio), e identificar cuántas y cuáles realizó cada encuestador.</p>{error&&<p role="alert">{error}</p>}
 <div style={{margin:'18px 0',border:'1px solid #dce6e2',borderRadius:14,padding:16}}><h2 style={{marginTop:0}}>Encuestas válidas por encuestador</h2>{porEncuestador.length===0?<p>No hay encuestas finalizadas válidas.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={st}>Encuestador</th><th style={st}>Cantidad</th><th style={st}>Códigos de encuestas</th><th style={st}>Acción</th></tr></thead><tbody>{porEncuestador.map(x=><tr key={x.id}><td style={st}><strong>{x.id}</strong></td><td style={st}><strong>{x.total}</strong></td><td style={st}>{x.folios.join(', ')}</td><td style={st}><button type="button" onClick={()=>verEncuestador(x.id)} style={{padding:'7px 10px'}}>VER ENCUESTAS</button></td></tr>)}</tbody></table></div>}</div>
 <div id="listado-encuestas" style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:10,margin:'16px 0'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por código, establecimiento, municipio, ECOR o encuestador" style={{padding:10,border:'1px solid #bdcbc6',borderRadius:8}}/><select value={estado} onChange={e=>setEstado(e.target.value)} style={{padding:10,border:'1px solid #bdcbc6',borderRadius:8}}><option value="ENVIADA">Finalizadas válidas</option><option value="">Todos los estados</option><option value="EN_CURSO">En curso</option><option value="CANCELADA">Canceladas</option></select><select value={encuestador} onChange={e=>setEncuestador(e.target.value)} style={{padding:10,border:'1px solid #bdcbc6',borderRadius:8}}><option value="">Todos los encuestadores</option>{porEncuestador.map(x=><option key={x.id} value={x.id}>{x.id} ({x.total})</option>)}</select></div>
 {encuestador&&<p><strong>Encuestador seleccionado:</strong> {encuestador} · <button type="button" onClick={()=>setEncuestador('')} style={{padding:'5px 8px'}}>QUITAR FILTRO</button></p>}
 <p><strong>{filtrada.length}</strong> encuesta(s).</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={st}>Código</th><th style={st}>Fecha</th><th style={st}>Encuestador</th><th style={st}>Tipo</th><th style={st}>Establecimiento</th><th style={st}>Municipio / ECOR</th><th style={st}>Estado</th><th style={st}>Acción</th></tr></thead><tbody>{filtrada.map(x=><tr key={x.sesion_id}><td style={st}><strong>{x.folio}</strong></td><td style={st}>{String(x.enviada_at||x.iniciada_at||'').replace('T',' ').slice(0,16)}</td><td style={st}>{x.encuestador_id||'—'}</td><td style={st}>{x.tipo_encuesta}</td><td style={st}>{x.establecimiento_nombre}</td><td style={st}>{x.municipio||'—'} / {x.ecor||'—'}</td><td style={st}>{x.estado}</td><td style={st}><button type="button" onClick={()=>setSel(x)} style={{padding:'7px 10px'}}>REVISAR</button></td></tr>)}</tbody></table></div>
 {sel&&<div style={{marginTop:24,border:'1px solid #dce6e2',borderRadius:14,padding:16}}><button type="button" onClick={()=>setSel(null)} style={{float:'right',padding:'6px 10px'}}>CERRAR</button><h2>Encuesta {sel.folio}</h2><p><strong>Estado:</strong> {sel.estado} · <strong>Tipo:</strong> {sel.tipo_encuesta}<br/><strong>Establecimiento:</strong> {sel.establecimiento_nombre}<br/><strong>Municipio / ECOR:</strong> {sel.municipio||'—'} / {sel.ecor||'—'}<br/><strong>Encuestador:</strong> {sel.encuestador_id||'—'}</p>{sel.estado==='ENVIADA'?<>{respuestas.length===0?<p>Sin respuestas disponibles.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={st}>#</th><th style={st}>Dimensión</th><th style={st}>Pregunta</th><th style={st}>Respuesta</th></tr></thead><tbody>{respuestas.map(r=><tr key={`${r.sesion_id}-${r.pregunta_id}`}><td style={st}>{r.orden}</td><td style={st}>{r.dimension||'—'}</td><td style={st}>{r.pregunta}</td><td style={st}><strong>{val(r.respuesta)}</strong></td></tr>)}</tbody></table></div>}</>:<p>Esta encuesta no es una encuesta finalizada válida y no se contabiliza en los reportes.</p>}</div>}
 <div style={{display:'flex',gap:10,marginTop:18,flexWrap:'wrap'}}><a className="button" href="/reportes">REPORTES</a><a className="button" href="/panel">VOLVER AL PANEL</a></div></section></main>;
}