'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../utils/supabase/client';
const vacio={nombre:'',email:'',telefono:'',password:'',confirmar_password:'',es_externo_sesal:true};
export default function Page(){const router=useRouter();const[items,setItems]=useState([]),[form,setForm]=useState(vacio),[rol,setRol]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[creando,setCreando]=useState(false);const inp={width:'100%',padding:'11px',marginTop:'5px'};
async function cargar(){const s=createClient();const{data,error:e}=await s.rpc('listar_encuestadores_admin');if(e)setError(e.message);else setItems(Array.isArray(data)?data:[])}
useEffect(()=>{let a=true;(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data}=await s.rpc('obtener_mi_perfil');const p=Array.isArray(data)?data[0]:null;if(!p||!['ADMIN_GENERAL','ADMIN_ENCUESTAS','JEFE_ENCUESTADORES'].includes(p.rol)||!p.activo){router.replace('/panel');return}if(!a)return;setRol(p.rol);await cargar();if(a)setLoading(false)})();return()=>{a=false}},[router]);
const puede=rol==='ADMIN_GENERAL'||rol==='ADMIN_ENCUESTAS';const cambia=(c,v)=>setForm(f=>({...f,[c]:v}));
async function crear(e){e.preventDefault();setError('');setMensaje('');if(form.password.length<8){setError('La contraseña debe tener al menos 8 caracteres.');return}if(form.password!==form.confirmar_password){setError('Las contraseñas no coinciden.');return}setCreando(true);const s=createClient();const{data,error:fe}=await s.functions.invoke('crear-encuestador',{body:form});if(fe||!data?.ok){setError(data?.error||fe?.message||'No fue posible crear el encuestador.');setCreando(false);return}setMensaje(`Encuestador creado. ID permanente: ${data.encuestador_id}. Ahora puede ser designado a una o varias unidades desde DESIGNAR ENCUESTADORES.`);setForm(vacio);await cargar();setCreando(false)}
return <main className="shell"><section className="loginCard" style={{maxWidth:'900px'}}><div className="badge">ENCUESTAS · OLANCHO</div><h1>Gestionar encuestadores</h1><p>La creación del encuestador es independiente de sus lugares de trabajo. Un mismo encuestador puede recibir varias designaciones.</p>{puede&&<form onSubmit={crear} style={{border:'2px solid #17634e',borderRadius:'14px',padding:'18px',margin:'20px 0'}}><h2>Crear encuestador</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:'12px'}}><label>Nombre completo<input required value={form.nombre} onChange={e=>cambia('nombre',e.target.value)} style={inp}/></label><label>Correo electrónico / Usuario<input required type="email" value={form.email} onChange={e=>cambia('email',e.target.value)} style={inp}/></label><label>Número de teléfono<input required type="tel" value={form.telefono} onChange={e=>cambia('telefono',e.target.value)} style={inp}/></label><label>Contraseña<input required type="password" minLength={8} value={form.password} onChange={e=>cambia('password',e.target.value)} style={inp}/></label><label>Verificar contraseña<input required type="password" minLength={8} value={form.confirmar_password} onChange={e=>cambia('confirmar_password',e.target.value)} style={inp}/></label></div><label style={{display:'block',marginTop:'12px',fontWeight:700}}><input type="checkbox" required checked={form.es_externo_sesal} onChange={e=>cambia('es_externo_sesal',e.target.checked)}/> Confirmo que el encuestador es externo a la Secretaría de Salud</label><button disabled={creando||!form.es_externo_sesal} style={{marginTop:'16px',width:'100%'}}>{creando?'CREANDO…':'CREAR ENCUESTADOR'}</button></form>}{puede&&<a className="button" href="/designaciones" style={{display:'block',margin:'12px 0'}}>DESIGNAR ENCUESTADORES</a>}{mensaje&&<p role="status"><strong>{mensaje}</strong></p>}{loading&&<p>Cargando…</p>}{error&&<p role="alert">{error}</p>}{!loading&&items.map(i=><div key={i.usuario_id} style={{border:'1px solid #dce6e2',borderRadius:'12px',padding:'16px',margin:'12px 0'}}><p><strong>{i.nombre||'Encuestador'}</strong> · {i.encuestador_id}</p><p><strong>Teléfono:</strong> {i.telefono||'—'}</p><p><strong>Estado:</strong> {i.activo?'Activo':'Inactivo'}</p></div>)}<a className="back" href="/panel">← Volver al panel</a></section></main>}
