'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '../../utils/supabase/client';

const vacio = { nombre:'', email:'', municipio:'', establecimiento_codigo:'', establecimiento_nombre:'', tipo_encuesta:'', hospital:false, es_externo_sesal:true };

export default function EncuestadoresPage() {
  const router = useRouter();
  const [items,setItems]=useState([]), [municipios,setMunicipios]=useState([]), [establecimientos,setEstablecimientos]=useState([]);
  const [loading,setLoading]=useState(true), [error,setError]=useState(''), [mensaje,setMensaje]=useState(''), [rol,setRol]=useState('');
  const [form,setForm]=useState(vacio), [creando,setCreando]=useState(false), [cargandoEstablecimientos,setCargandoEstablecimientos]=useState(false);

  async function cargar(){ const s=createClient(); const {data,error:e}=await s.rpc('listar_encuestadores_admin'); if(e)setError('No fue posible cargar los encuestadores.'); else setItems(Array.isArray(data)?data:[]); }
  async function cargarMunicipios(){ const s=createClient(); const {data,error:e}=await s.rpc('listar_municipios_encuestas'); if(e){setError('No fue posible cargar los municipios.');return;} setMunicipios((Array.isArray(data)?data:[]).map(x=>x.municipio)); }
  async function cargarEstablecimientos(m){ setEstablecimientos([]); if(!m)return; setCargandoEstablecimientos(true); const s=createClient(); const {data,error:e}=await s.rpc('listar_establecimientos_municipio_encuestas',{p_municipio:m}); if(e)setError('No fue posible cargar los establecimientos del municipio.'); else setEstablecimientos(Array.isArray(data)?data:[]); setCargandoEstablecimientos(false); }

  useEffect(()=>{let active=true;(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return;}const {data}=await s.rpc('obtener_mi_perfil');const p=Array.isArray(data)?data[0]:null;if(!p||!['ADMIN_GENERAL','ADMIN_ENCUESTAS','JEFE_ENCUESTADORES'].includes(p.rol)||!p.activo){router.replace('/panel');return;}if(!active)return;setRol(p.rol);await Promise.all([cargar(),cargarMunicipios()]);if(active)setLoading(false);})();return()=>{active=false};},[router]);

  const soloConsulta=rol==='JEFE_ENCUESTADORES', puedeCrear=rol==='ADMIN_GENERAL'||rol==='ADMIN_ENCUESTAS';
  function cambia(c,v){setForm(f=>({...f,[c]:v}));}
  async function seleccionarMunicipio(v){setForm(f=>({...f,municipio:v,establecimiento_codigo:'',establecimiento_nombre:'',hospital:false,tipo_encuesta:''}));setError('');await cargarEstablecimientos(v);}
  function seleccionarEstablecimiento(codigo){const x=establecimientos.find(e=>e.codigo===codigo);if(!x){setForm(f=>({...f,establecimiento_codigo:'',establecimiento_nombre:'',hospital:false,tipo_encuesta:''}));return;}const h=!!x.hospital;setForm(f=>({...f,establecimiento_codigo:x.codigo,establecimiento_nombre:x.nombre,hospital:h,tipo_encuesta:h?'HOSPITALIZACION':'AMBULATORIA'}));}

  async function crearEncuestador(e){e.preventDefault();setError('');setMensaje('');setCreando(true);if(!form.municipio||!form.establecimiento_codigo){setError('Seleccione municipio y establecimiento u hospital.');setCreando(false);return;}if((form.hospital&&form.tipo_encuesta!=='HOSPITALIZACION')||(!form.hospital&&form.tipo_encuesta!=='AMBULATORIA')){setError('El tipo de encuesta no corresponde al establecimiento seleccionado.');setCreando(false);return;}const s=createClient();const {data,error:fe}=await s.functions.invoke('crear-encuestador',{body:form});if(fe||!data?.ok){setError(data?.error||fe?.message||'No fue posible crear el encuestador.');setCreando(false);return;}setMensaje(`Encuestador creado correctamente. ID permanente: ${data.encuestador_id}. Se envió invitación al correo indicado.`);setForm(vacio);setEstablecimientos([]);await cargar();setCreando(false);}
  async function cambiarEstado(item){const motivo=window.prompt(item.activo?'Motivo para inactivar al encuestador:':'Motivo para reactivar al encuestador:');if(motivo===null)return;const s=createClient();const {error:e}=await s.rpc('cambiar_estado_encuestador',{p_usuario_id:item.usuario_id,p_activo:!item.activo,p_motivo:motivo.trim()||null});if(e){setError(e.message);return;}setMensaje(item.activo?'Encuestador inactivado.':'Encuestador reactivado.');await cargar();}

  return <main className="shell"><section className="loginCard" style={{maxWidth:'900px'}}><div className="badge">ENCUESTAS · OLANCHO</div><h1 style={{fontSize:'34px'}}>{soloConsulta?'Encuestadores asignados':'Gestionar encuestadores'}</h1><p>{soloConsulta?'Consulta operativa para supervisión y asignación del tipo de encuesta.':rol==='ADMIN_ENCUESTAS'?'Administración de encuestadores dentro del alcance autorizado.':'Administración general de asignaciones de encuestadores.'}</p>
  <div style={{background:'#f7faf9',border:'1px solid #dce6e2',borderRadius:'12px',padding:'14px',margin:'18px 0'}}><strong>Reglas vigentes</strong><p style={{margin:'8px 0 0'}}>Cada encuestador debe ser externo a SESAL y conservar un ID único permanente. Las unidades de salud aplican Atención Ambulatoria; los hospitales aplican Hospitalización / Internamiento.</p></div>
  {puedeCrear&&<form onSubmit={crearEncuestador} style={{border:'2px solid #17634e',borderRadius:'14px',padding:'18px',margin:'20px 0'}}><h2 style={{marginTop:0}}>Crear encuestador</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:'12px'}}>
  <label>Nombre completo<input required value={form.nombre} onChange={e=>cambia('nombre',e.target.value)} style={{width:'100%',padding:'11px',marginTop:'5px'}}/></label><label>Correo electrónico<input required type="email" value={form.email} onChange={e=>cambia('email',e.target.value)} style={{width:'100%',padding:'11px',marginTop:'5px'}}/></label>
  <label>Municipio<select required value={form.municipio} onChange={e=>seleccionarMunicipio(e.target.value)} style={{width:'100%',padding:'11px',marginTop:'5px'}}><option value="">Seleccione municipio</option>{municipios.map(m=><option key={m} value={m}>{m}</option>)}</select></label>
  <label>Unidad de salud u hospital<select required disabled={!form.municipio||cargandoEstablecimientos} value={form.establecimiento_codigo} onChange={e=>seleccionarEstablecimiento(e.target.value)} style={{width:'100%',padding:'11px',marginTop:'5px'}}><option value="">{cargandoEstablecimientos?'Cargando…':'Seleccione establecimiento'}</option>{establecimientos.map(es=><option key={es.codigo} value={es.codigo}>{es.hospital?'HOSPITAL · ':`${es.tipo} · `}{es.nombre}{es.hospital?'':` · RUPS ${es.codigo}`}</option>)}</select></label>
  <label>Tipo de encuesta<input readOnly value={form.tipo_encuesta==='HOSPITALIZACION'?'Hospitalización / Internamiento':form.tipo_encuesta==='AMBULATORIA'?'Atención Ambulatoria':''} placeholder="Se asigna automáticamente" style={{width:'100%',padding:'11px',marginTop:'5px',background:'#f3f6f5'}}/></label></div>
  {form.establecimiento_codigo&&<p style={{fontSize:'13px',color:'#647a74',margin:'10px 0 0'}}><strong>Asignación:</strong> {form.establecimiento_nombre}{form.hospital?' · Hospital':` · RUPS ${form.establecimiento_codigo}`}</p>}
  <label style={{display:'block',marginTop:'10px',fontWeight:700}}><input type="checkbox" required checked={form.es_externo_sesal} onChange={e=>cambia('es_externo_sesal',e.target.checked)}/> Confirmo que el encuestador es externo a la Secretaría de Salud</label><button type="submit" disabled={creando||!form.es_externo_sesal||!form.establecimiento_codigo} style={{marginTop:'16px',width:'100%'}}>{creando?'CREANDO…':'CREAR ENCUESTADOR'}</button><p style={{fontSize:'13px',color:'#647a74'}}>El tipo de encuesta se asigna automáticamente según el establecimiento seleccionado.</p></form>}
  {mensaje&&<p role="status" style={{background:'#eef7f3',border:'1px solid #9fcdbd',padding:'12px',borderRadius:'10px'}}><strong>{mensaje}</strong></p>}{loading&&<p>Cargando…</p>}{error&&<p role="alert" style={{background:'#fff1f0',border:'1px solid #d99',padding:'12px',borderRadius:'10px'}}>{error}</p>}
  {!loading&&!error&&items.length===0&&<div style={{border:'1px dashed #bdcbc6',borderRadius:'12px',padding:'18px',margin:'18px 0'}}><strong>Aún no hay encuestadores asignados.</strong></div>}
  {!loading&&items.map(item=><div key={`${item.usuario_id}-${item.encuestador_id}-${item.fecha_asignacion}`} style={{border:'1px solid #dce6e2',borderRadius:'12px',padding:'16px',margin:'14px 0'}}><p><strong>{item.nombre||'Encuestador'}</strong> · {item.encuestador_id}</p><p><strong>Asignación:</strong> {item.establecimiento_nombre} {item.hospital?'(Hospital)':''}</p><p><strong>Código:</strong> {item.establecimiento_codigo}</p><p><strong>Tipo:</strong> {item.tipo_encuesta==='AMBULATORIA'?'Atención Ambulatoria':'Hospitalización / Internamiento'}</p><p><strong>Estado:</strong> {item.activo?'Activo':'Inactivo'}</p>{!soloConsulta&&<button type="button" onClick={()=>cambiarEstado(item)}>{item.activo?'INACTIVAR':'REACTIVAR'}</button>}</div>)}<a className="back" href="/panel">← Volver al panel</a></section></main>;
}
