import { NextResponse } from 'next/server';
import { requireVigilanciaUser, scopeAllows } from '../../../../utils/vigilancia/server';

export async function GET(request){
 const access=await requireVigilanciaUser(request);if(access.error)return NextResponse.json({error:access.error},{status:access.status});const id=new URL(request.url).searchParams.get('id');
 const {data:b,error}=await access.admin.from('vigilancia_boletines').select('*,vigilancia_clinicas(id,codigo,nombre,municipio)').eq('id',id).maybeSingle();if(error||!b)return NextResponse.json({error:'Boletín no encontrado.'},{status:404});if(!scopeAllows(access.perfil,b.vigilancia_clinicas?.municipio,b.clinica_id))return NextResponse.json({error:'Fuera de su cobertura.'},{status:403});
 const [{data:catalog},{data:counts}]=await Promise.all([access.admin.from('vigilancia_enfermedades').select('codigo,nombre,orden').eq('activa',true).order('orden'),access.admin.from('vigilancia_conteos').select('*').eq('boletin_id',id)]);return NextResponse.json({boletin:b,enfermedades:catalog||[],conteos:counts||[],puede_modificar:['ADMIN_GENERAL','VIGILANCIA_REGIONAL'].includes(access.perfil.rol)});
}

export async function PATCH(request){
 const access=await requireVigilanciaUser(request,new Set(['ADMIN_GENERAL','VIGILANCIA_REGIONAL']));if(access.error)return NextResponse.json({error:access.error},{status:access.status});const body=await request.json(),id=String(body.id||''),motivo=String(body.motivo||'').trim();if(!motivo)return NextResponse.json({error:'El motivo de la modificación es obligatorio.'},{status:400});
 const {data:b}=await access.admin.from('vigilancia_boletines').select('*').eq('id',id).maybeSingle();if(!b)return NextResponse.json({error:'Boletín no encontrado.'},{status:404});const {data:before}=await access.admin.from('vigilancia_conteos').select('*').eq('boletin_id',id);const map=new Map((before||[]).map(x=>[x.enfermedad_codigo,x]));const rows=[];
 for(const[code,raw]of Object.entries(body.conteos||{})){const value=Number(raw),previous=map.get(code);if(!Number.isInteger(value)||value<0||value<Number(previous?.casos_inmediatos||0))return NextResponse.json({error:`Conteo no válido para ${code}.`},{status:400});rows.push({boletin_id:id,enfermedad_codigo:code,cantidad:value,casos_inmediatos:Number(previous?.casos_inmediatos||0),updated_at:new Date().toISOString()})}
 const up=await access.admin.from('vigilancia_conteos').upsert(rows,{onConflict:'boletin_id,enfermedad_codigo'});if(up.error)return NextResponse.json({error:'No fue posible actualizar los conteos.'},{status:500});await access.admin.from('vigilancia_boletines').update({modificado_despues_cierre:b.estado==='CERRADO'||b.modificado_despues_cierre,motivo_modificacion:motivo,updated_at:new Date().toISOString()}).eq('id',id);const{data:after}=await access.admin.from('vigilancia_conteos').select('*').eq('boletin_id',id);await access.admin.from('vigilancia_auditoria').insert({tabla:'vigilancia_boletines',registro_id:id,accion:'CORRECCION_POSTERIOR',usuario_id:access.user.id,clinica_id:b.clinica_id,antes:{boletin:b,conteos:before},despues:{conteos:after},motivo,origen:'API'});return NextResponse.json({ok:true});
}
